In [1]:
import pandas as pd
import numpy as np

In [2]:
data={
    "Category": ["Parent", "Male", "Female", "Science", "Arts"],
    "Interested": [20, 10, 10, 10, 10],
    "Not_Interested": [30, 20, 10, 30, 0],
    "Total": [50, 30, 20, 40, 10]
}

df=pd.DataFrame(data)
df

  Category  Interested  Not_Interested  Total
0   Parent          20              30     50
1     Male          10              20     30
2   Female          10              10     20
3  Science          10              30     40
4     Arts          10               0     10

In [5]:
def gini_from_row(row):
    p1=row["Interested"]/row["Total"]
    p2=row["Not_Interested"]/row["Total"]
    return 1-(p1**2+p2**2)

In [6]:
df["Gini"]=df.apply(gini_from_row, axis=1)
df

  Category  Interested  Not_Interested  Total      Gini
0   Parent          20              30     50  0.480000
1     Male          10              20     30  0.444444
2   Female          10              10     20  0.500000
3  Science          10              30     40  0.375000
4     Arts          10               0     10  0.000000

In [8]:
parent_gini=df[df["Category"]=="Parent"]["Gini"].values[0]
print("Gini (Parent):", round(parent_gini, 3))

Gini (Parent): 0.48

In [15]:
male=df[df["Category"]=="Male"].iloc[0]
female=df[df["Category"]=="Female"].iloc[0]
total = df[df["Category"] == "Parent"]["Total"].values[0]

weighted_gender=(
    (male["Total"]/total)*male["Gini"]+(female["Total"]/total)*female["Gini"]
)

print("Weighted Gini (Gender Split):", round(weighted_gender, 3))

Weighted Gini (Gender Split): 0.467

In [16]:
science=df[df["Category"]=="Science"].iloc[0]
arts=df[df["Category"]=="Arts"].iloc[0]

weighted_stream=(
    (science["Total"]/total)*science["Gini"]+(arts["Total"]/total)*arts["Gini"]
)

print("Weighted Gini (Stream Split):", round(weighted_stream, 3))

Weighted Gini (Stream Split): 0.3

In [17]:
print("Parent Gini:", round(parent_gini, 3))
print("Weighted Gender Gini:", round(weighted_gender, 3))
print("Weighted Stream Gini:", round(weighted_stream, 3))

if weighted_stream<weighted_gender:
    print("Better Split: Stream")
else:
    print("Better Split: Gender")

Parent Gini: 0.48
Weighted Gender Gini: 0.467
Weighted Stream Gini: 0.3
Better Split: Stream